project:
  type: website
  resources:
    - exercises.zip

website:
  page-navigation: true
  title: "Dynamic Documents: Quarto"
  description: "RT2 Short Workshop - Quarto"

  repo-url: https://github.com/quarto-rt2/quarto-rt2
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#D1D9E3"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/quarto-rt2/quarto-rt2
        text: "GitHub organization"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: pre-work.qmd
        text: Pre-work
      - section: "Modules"
        contents:
          - href: 1-hello-quarto/index.qmd
            text: Hello Quarto
          - href: 2-documents/index.qmd
            text: Documents
          - href: 3-presentations/index.qmd
            text: Presentations
          - href: 4-websites/index.qmd
            text: Websites

  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel + Andrew Bray"
    background: "#D1D9E3" # Arylide Yellow

format:
  html:
    theme:
      light: [sandstone, style/sta313.scss]
      dark: [sandstone, style/sta313.scss, style/dark.scss]
    linkcolor: "#58779b"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto
