project:
  type: website

website:
  page-navigation: true
  title: "From R Markdown to Quarto"
  description: "ASA Travelling Workshop"
  repo-url: https://github.com/andrewpbray/quarto-asa
  page-footer:
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel + Andrew Bray"
    center:
      - icon: github
        href: https://github.com/andrewpbray/quarto-asa
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
  open-graph: true
  sidebar:
    background: "#D1D9E3"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: pre-work.qmd
        text: Pre-work
      - text: "---"
      - section: "Producing a Single Document"
        contents:
          - href: 1-hello-quarto/index.qmd
            text: Hello Quarto
          - href: 2-documents/index.qmd
            text: Documents
          - href: 3-presentations/index.qmd
            text: Presentations
      - text: "---"
      - section: "Producing Websites and Books"
        contents:
          - href: 4-websites/index.qmd
            text: Websites
          - href: 5-books/index.qmd
            text: Books
          - href: 6-miscellaneous/index.qmd
            text: Miscellaneous

format:
  html:
    theme:
      light: [sandstone, style/quarto-asa.scss]
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    toc: true

execute:
  freeze: auto
  echo: true